### PR TITLE
Change uses version

### PR DESCRIPTION
**Pull request by moonrope**
For few days I was following the documentation and use anmol098/waka-readme-stats@master in my action file but it did't work, then I use the anmol098/waka-readme-stats@V1.1 and it works.
I add that change in the documentation.

### CODE REVIEW

**Comment by anmol098** [comment]
Hello there.. I am not able to get exactly which line you made change to.. Can you please specify that...

**Comment by moonrope** [comment]
> Hello there.. I am not able to get exactly which line you made change to.. Can you please specify that...

Sorry for not been clear, you can find the explanation in the comment. #37

**Comment by anmol098** [comment]
I got the explanation... But same steps worked for everyone... Infact I am also using the same steps.. As I prescribed in the documentation... Can you use the same steps and give the error from the log which you are getting... So that we can be able to fix that.

**Comment by anmol098** [comment]
cannot merge because none user reported that bug

**Pull request closed without merging**
