### PR TITLE
add new version of symbol block & empty

### PR DESCRIPTION
**Pull request by oHTGo**
Hi, I'm Lil Huy. Today I want to contribute a pull request.
I realize that currently, the symbol block and empty can be uneven in some devices, so after I found 2 other good characters to use, I tested them and it seems to work for both Windows, Linux, and mobile.

**Old symbol version**
image
Old version will skew when displayed on Windows

**New symbol version**
image

I hope to accept this pull request. Thanks.

### CODE REVIEW

**Comment by oHTGo** [comment]
@anmol098 you can test more to make sure this PR works well

**Comment by aravindvnair99** [comment]
@oHTGo check #213

**Comment by aravindvnair99** [comment]
Issue #211

**Comment by oHTGo** [comment]
@aravindvnair99 I get it, but it looks like my symbol can fix these

**Comment by aravindvnair99** [comment]
> @aravindvnair99 I get it, but it looks like my symbol can fix these. Can you test it for me to see if it still happens?

@oHTGo LGTM on Windows 11 and Android 12. I unfortunately am not near a Apple or Linux system at the moment.

**Review by aravindvnair99 — COMMENTED** [review]
@oHTGo LGTM on Windows 11 and Android 12. I unfortunately am not near a Apple or Linux system at the moment.

**Comment by oHTGo** [comment]
Wait for people to test more to know how?

**Review by aravindvnair99 — APPROVED** [review]
@oHTGo I just checked on macOS and Ubuntu as well. Looks good. Only iPhone is pending.

**Comment by oHTGo** [comment]
@aravindvnair99 hope these are 2 good symbols for all devices.

**Review by bastianleicht — APPROVED** [review]
Pretty simple, but worked on all my devices :) Please merge!

**Review by kaazima — APPROVED** [review]
I checked on Windows 11, Ubuntu, macOS, and Android. It worked on all my devices too.

**Comment by anmol098** [comment]
@oHTGo Thanks for making the design improvemnts. 

@aravindvnair99 @kaazima @bastianleicht Thanks for reviewing and testing out this pull request.

Merging.

**Comment by aravindvnair99** [comment]
> @oHTGo Thanks for making the design improvemnts.
> 
> @aravindvnair99 @kaazima @bastianleicht Thanks for reviewing and testing out this pull request.
> 
> Merging.

@anmol098 Happy to help! Issue #211 can also be closed as this PR has been merged and this fixes that. Another related PR is #213 which was trying to fix same issue.

**Pull request merged**
