### PR TITLE
Fixed commit pagination code

### PR DESCRIPTION
**Pull request by pseusys**
Here I found (and hopefully fixed) pagination bug, that was found using @StasonMendelso hints and efforts.
Could you please check if the current version is correct (especially the *commit count*)?

### CODE REVIEW

**Comment by StasonMendelso** [comment]
Hello! 
I've tried to run this branch in my workflow and it's finished successfully, but there were still wrong number of commits. However, I  could incorrectly run action. I've only changed wakatimestats.yml file and it looks like on the image. I have no experience in action's files.
image
After I pushed it to github and ru action manually. I've the next logs and it seems strange, why image pulled from master branch. Is it Ok?
[logs_14.zip](https://github.com/anmol098/waka-readme-stats/files/12319752/logs_14.zip)
In addition, I've calculated all my commits, which this action generated in time section: 
image
The sum is **3.794**. 

After I saw a real total number of commits in my profile from stats, which I [use](https://github-readme-stats-sigma-five.vercel.app). I think, it's a correct number, because I haven't got so much number of commits.
image

So, the real number of commits from stats is **431**.
I've divided it and have: **3.794/431 = 8,8027**. Maybe, there can be another relation between numbers.
Maybe, it can help.

**Comment by pseusys** [comment]
@StasonMendelso, here's what I found:
1. Yes, you're right, for now using any particular branch of the action will use the same main Docker image. Idk if this can be changed - this is the matter of future investigation if you're interested.
2. [This comment](https://github.com/anmol098/waka-readme-stats/discussions/466#discussioncomment-6697872) describes how the action counts the commit number.
    We have never discussed that, however that might be problematic. Calculating commits like this, e.g. will calculate commits on **merged, but not deleted branches twice**. Same might happen about GitHub pages branch, co-authored commits, etc.
    Again, we can switch to calculating only **main** branch commits. However, that can be also problematic if e.g. user has only contributed to not-main branch (e.g. repository has `v1` and `v2` branches, both are supported, `v2` is marked as main, but user has contributed to `v1`, see [this](https://github.com/ros/ros) repo for example). This can also be problematic in case of long-lasting PRs, if a PR takes a year to merge the stats will be there only after it's merged.
    @anmol98, @aravindvnair99 what are your opinions on how user commits should be counted?

**Comment by pseusys** [comment]
In order to pull different images on different repository branches we have to modify [this](https://github.com/anmol098/waka-readme-stats/blob/f8cec5f73e6f2a551a25da883d849b06f471a918/action.yml#L152) line so that:

1. On `master` branch it would be `docker://wakareadmestats/waka-readme-stats:master`
2. On every release it would be `docker://wakareadmestats/waka-readme-stats:[RELEASE_TAG]`
3. On every other branch it would be `Dockerfile`

In order to do that, we can:

1. Check and if needed change the source file on every push with GitHub action (I like this less)
2. Create a `make` target to setup pre-commit hooks to change the source file + check if the source file is correct on every push with GitHub action (and fail if it's not)

**Review by anmol098 — APPROVED** [review]
lgtm

**Pull request merged**
