### PR TITLE
Difference between additions and deletions

### LINKED ISSUE #245: bar_graph.png is wrong
**Describe the bug**
| date | pic |
| --- | --- |
| Nov 26, 2021 | [link](https://github.com/Arondight/Arondight/blob/b1e624b78a71505900c64815b56db564b66c6092/charts/bar_graph.png) |
| Dec 6, 2021 | [link](https://github.com/Arondight/Arondight/blob/0e05d29908335e704b8ce491caf5c75ec7aafe67/charts/bar_graph.png) |

Obviously this is wrong, and **why is there a negative 5000**?

**To Reproduce**

**Expected behavior**

**Github repository link**
https://github.com/Arondight/Arondight

**Additional context**

### LINKED ISSUE #307: FEAT Disable code timeline
I am having trouble figuring out how to disable the timeline at the end of the README.md. Could you help me with that? Thank you!

### PR DESCRIPTION
**Pull request by pseusys**
Additions and deletions calculation changed, graph drawing algorithm enchanced:
- Not only the difference is stored, but both additions and deletions values.
- Lines of code badge demonstrates **additions** sum now.
- Lines of code graph demonstrates both additions and deletions.

Presumably closes #245
Presumably closes #307

### CODE REVIEW

**Review by aravindvnair99 — COMMENTED** [review]
@pseusys the image looks blank to me? Is it the same for you?

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
We have a negative graph:

image

**Review by aravindvnair99 — DISMISSED** [review]
@pseusys could we add a negative axis to make it clear that those are deletions?

**Comment by anmol098** [comment]
> @pseusys could we add a negative axis to make it clear that those are deletions?

@aravindvnair99 long back we tried with negative axis to show deletion. That makes the graph look weird if user has done code refactoring In a quarter the bar goes down and down at negative. Making the image not look good.
.
Instead of barchart we can give a try to line chart where 2 lines will more for addition and deletion respectively what are your thaughts?? @pseusys

**Review by anmol098 — APPROVED** [review]

**Comment by anmol098** [comment]
Can we add a chart like this any thaughts ?
Screenshot 2023-03-11 at 14 12 50

**Pull request merged**
