### PR TITLE
Updates waka stats format using tables #211

### LINKED ISSUE #211: Empty block ░  is messed up
From the very beginning, I found that the empty block ░ for bar graphs messes with the output.
<p>

error
</p>
I have tried it on my friends' computer, different browser but it shows a similar problem. Even your readme preview have such messed up output. However, I get the expected output when I open it in Chrome for Android.
<br><br>

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to my[ GitHub profile](https://github.com/Mitrajit) readme 

**Expected behaviour**
Screenshot taken from my android device

**Github repository link**
https://github.com/Mitrajit

This might be a resolution related problem and hopefully, you will come up with a solution.
Thank you.

### PR DESCRIPTION
**Pull request by Mitrajit**
fixes  #211 

**Changes made**
Used tables instead of text highlight because the blank space of the progress bar produced messy output in low resolution screen.

**Screenshots**
image
image

@aravindvnair99 @anmol098 requesting a review.

### CODE REVIEW

**Review by aravindvnair99 — APPROVED** [review]
@Mitrajit I tested your PR on Windows, Android and iOS, and it is working as expected. I currently don't have my Mac with me to test. LGTM otherwise.

**Comment by Mitrajit** [comment]
@anmol098 Any updates?

**Comment by bastianleicht** [comment]
@Mitrajit Tested it and it looks very good. But you might consider it to be an optional Setting.

**Comment by Mitrajit** [comment]
@bastianleicht as of now it seems to be optional only. If you want to use tables in your readme consider using my fork `Mitrajit/waka-readme-stats@Fix-for-messy-progress-bars`

**Comment by anmol098** [comment]
@Mitrajit looks perfectly fine Thanks for the update and sorry for seeing this very late
will merge this. but thinking of one more tweak in this if we can have two display options one is the old UI and the other with a tabular one we have a flag for the same to switch between the UI. @aravindvnair99 what do you have to say?

**Comment by Mitrajit** [comment]
@anmol098 @aravindvnair99 You might push commits(for adding a flag) to this PR and merge the changes. I have allowed edits by maintainers.

**Comment by ppizarror** [comment]
> Excuse me, when will this PR be merged?

I have the same doubt

**Comment by Mitrajit** [comment]
@oHTGo @ppizarror You guys can use consider using my fork `Mitrajit/waka-readme-stats@Fix-for-messy-progress-bars`. Just replace `- uses: anmol098/waka-readme-stats@master` with `- uses: Mitrajit/waka-readme-stats@Fix-for-messy-progress-bars`

**Comment by aravindvnair99** [comment]
> @Mitrajit looks perfectly fine Thanks for the update and sorry for seeing this very late will merge this. but thinking of one more tweak in this if we can have two display options one is the old UI and the other with a tabular one we have a flag for the same to switch between the UI. @aravindvnair99 what do you have to say?

@anmol098 Sorry for the late response. Considering the new UI works on all devices and the old UI does not, I'm in favour of the new UI replacing the old UI than leaving it as a flag and have users wondering why something isn't working on a certain device.

> @anmol098 @aravindvnair99 You might push commits(for adding a flag) to this PR and merge the changes. I have allowed edits by maintainers.

Sorry @Mitrajit, I'm not a maintainer yet although I've contributed to this repository before and have reviewed and approved your pull request as well. Just another open-source enthusiast :)

**Comment by oHTGo** [comment]
> @oHTGo @ppizarror You guys can use consider using my fork `Mitrajit/waka-readme-stats@Fix-for-messy-progress-bars`. Just replace `- uses: anmol098/waka-readme-stats@master` with `- uses: Mitrajit/waka-readme-stats@Fix-for-messy-progress-bars`

Hmmm, I want to merge these contributions so that everyone can use them easily, as well as possible.

**Comment by Mitrajit** [comment]
Any updates on this? @anmol098

**Comment by aravindvnair99** [comment]
FYI: #266 has also solved the issue, but without tables.

**Comment by bastianleicht** [comment]
But this looks better :)

**Comment by pseusys** [comment]
@bastianleicht, as far as we are using README.md I would suggest preferring markdown syntax over HTML.
Let me know if the original issue was solved by any previous PRs.

**Comment by aravindvnair99** [comment]
Fixed in #266. Feel free to create a new ticket for any further issues.

**Pull request closed without merging**
