### PR TITLE
Proper Casing and Tense for English

### PR DESCRIPTION
**Pull request by DanRowe1**
## Changes
- Verb tense of spend to spent in "This Week I Spent My Time On"
- Proper title casing for everything else
- Lines of code made lowercase because it will be preceded by "2.7 million" for example

### CODE REVIEW

**Comment by DanRowe1** [comment]
No problem.

**Comment by anmol098** [comment]
It looks good to me... But can you please modify this PR or create a new PR for the same.. Because.. You tried to edit the keys please don't do that..... In the json change only the value not the keys...
I think you should create a new PR only changing the values not the keys....

**Comment by DanRowe1** [comment]
I just updated this request instead of making a new PR. I have reverted all the keys back and only changed the values. I merged my fork with master so there's some new changes that will be hitting Alpha like the readme and the nonenglish translations. 
Accept if this is fine or let me know and I will make a new PR.  @anmol098

**Comment by anmol098** [comment]
Thanks
LGTM;
Merging

**Pull request merged**
